# Generated by Django 5.2.17 on 2026-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="catchup_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chore",
            name="recurrence_processed",
            field=models.BooleanField(default=False),
        ),
    ]
